### ISSUE TITLE
EscapingBoys are not so good

### ISSUE THREAD

**Issue by Lord-Kamina** [GraveofBears/GoodestBoy-Latest#6]
Hi. I absolutely love this mod (and thrice as much since the author of the "Dogs" mod decided to charge for it, more than the actual game costs)

However, I've noticed something that I think is a bug.

On several occasions I've found a Good boy on the forest at night, I befriend them and then morning comes... on a couple occasions I think they've outright despawned (Not sure, I was running with the dog behind me, I turn around and he's not there anymore).

On one other occasion, trying to prevent this, I took it out into the meadows, built a workbench and waited for morning while keeping him in sight. As soon as the day began, he became frightened and began running around chasing far away greylings. Eventually I caught up, made him stay, but nevertheless the dog literally jumped into the sea and began paddling away until he disappeared

On yet another occasion, my fiancé managed to bring one into one of our bases and while he hasn't despawned, he's constantly walking towards the walls as if he's trying to run away.

The only time I've succeeded in keeping one 100% is one I spawned from the console directly in my base, after the first one I found vanished into thin air.

Is this intended behavior or a bug? And if a bug, is it the mod's fault, or the base game?

**Comment by GraveofBears** [comment]
Sorry about that, was due to me setting their spawn time to Night, Valheim sets a behavior to creatures that spawn at night, to where they do run off and vanish.
